### ISSUE TITLE
Game still crashes when logging out

### ISSUE THREAD

**Issue by cherrybeans** [Gullskatten/beardblaster#58]
<img width="1362" alt="Screenshot 2021-04-14 at 23 50 52" src="https://user-images.githubusercontent.com/25204035/114785107-26c5b800-9db7-11eb-86f3-b3cfdfe0eb8c.png">

**Comment by gullskatten** [comment]
Det er på din branch? @cherrybeans  Kan ikke se at den gjør det på main.

**Comment by gullskatten** [comment]
Works on branch 'main'

![fixdd](https://user-images.githubusercontent.com/5576461/114906707-9c16a480-9e1a-11eb-8613-cc620f2dace1.gif)
